FLAGS = -std=c++17 -Wall

all: rec10-000-hierarchy-only rec10-001-num-pgs-000 rec10-002-correct-pgs \
	rec10-003-just-base-ctor rec10-004-ctor-correct rec10-005-dispNumLOgsInBase \
	rec10-006-bad-private rec10-007-indexpages rec10-008-a-PM-obj-disp \
	rec10-009-PM-obj-assgnd-T rec10-010-prt-PM-wo-virt rec10-011-virt \
	rec10-012-virt-ref rec10-013-abstract-first-try rec10-014-abstract-fixed \
	rec10-015-vector

rec10-000-hierarchy-only: rec10-000-hierarchy-only.cpp
	g++ ${FLAGS} -o rec10-000-hierarchy-only rec10-000-hierarchy-only.cpp

rec10-001-num-pgs-000: rec10-001-num-pgs-000.cpp
	g++ ${FLAGS} -o rec10-001-num-pgs-000 rec10-001-num-pgs-000.cpp

rec10-002-correct-pgs: rec10-002-correct-pgs.cpp
	g++ ${FLAGS} -o rec10-002-correct-pgs rec10-002-correct-pgs.cpp

rec10-003-just-base-ctor: rec10-003-just-base-ctor
	g++ ${FLAGS} -o rec10-003-just-base-ctor rec10-003-just-base-ctor.cpp

rec10-004-ctor-correct: rec10-004-ctor-correct.cpp
	g++ ${FLAGS} -o rec10-004-ctor-correct rec10-004-ctor-correct.cpp

rec10-005-dispNumLOgsInBase: rec10-005-dispNumLOgsInBase.cpp
	g++ ${FLAGS} -o rec10-005-dispNumLOgsInBase rec10-005-dispNumLOgsInBase.cpp

rec10-006-bad-private: rec10-006-bad-private.cpp
	g++ ${FLAGS} -o rec10-006-bad-private rec10-006-bad-private.cpp

rec10-007-indexpages: rec10-007-indexpages.cpp
	g++ ${FLAGS} -o rec10-007-indexpages rec10-007-indexpages.cpp

rec10-008-a-PM-obj-disp: rec10-008-a-PM-obj-disp.cpp
	g++ ${FLAGS} -o rec10-008-a-PM-obj-disp rec10-008-a-PM-obj-disp.cpp

rec10-009-PM-obj-assgnd-T: rec10-009-PM-obj-assgnd-T.cpp
	g++ ${FLAGS} -o rec10-009-PM-obj-assgnd-T rec10-009-PM-obj-assgnd-T.cpp

rec10-010-prt-PM-wo-virt: rec10-010-prt-PM-wo-virt.cpp
	g++ ${FLAGS} -o rec10-010-prt-PM-wo-virt rec10-010-prt-PM-wo-virt.cpp

rec10-011-virt: rec10-011-virt.cpp
	g++ ${FLAGS} -o rec10-011-virt rec10-011-virt.cpp

rec10-012-virt-ref: rec10-012-virt-ref.cpp
	g++ ${FLAGS} -o rec10-012-virt-ref rec10-012-virt-ref.cpp

rec10-013-abstract-first-try: rec10-013-abstract-first-try.cpp
	g++ ${FLAGS} -o rec10-013-abstract-first-try rec10-013-abstract-first-try.cpp

rec10-014-abstract-fixed: rec10-014-abstract-fixed.cpp
	g++ ${FLAGS} -o rec10-014-abstract-fixed rec10-014-abstract-fixed.cpp

rec10-015-vector: rec10-015-vector.cpp
	g++ ${FLAGS} -o rec10-015-vector rec10-015-vector.cpp

clean:
	rm -f rec10-000-hierarchy-only rec10-001-num-pgs-000 rec10-002-correct-pgs \
	rec10-003-just-base-ctor rec10-004-ctor-correct rec10-005-dispNumLOgsInBase \
	rec10-006-bad-private rec10-007-indexpages rec10-008-a-PM-obj-disp \
	rec10-009-PM-obj-assgnd-T rec10-010-prt-PM-wo-virt rec10-011-virt \
	rec10-012-virt-ref rec10-013-abstract-first-try rec10-014-abstract-fixed \
	rec10-015-vector
